apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  containers:
    - name: frontend
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/frontend:2.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    component: frontend
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    component: catalogue
spec:
  containers:
    - name: catalogue
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/catalogue:2.0.1
      env:
        - name: DOCUMENTDB
          value: "true"
        - name: MONGO_URL
          value: "mongodb://admin1:RoboShop123@prod-docdb.cluster-cbvsbeoyxek4.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    component: catalogue
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  containers:
    - name: cart
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/cart:2.0.0
      env:
        - name: REDIS_HOST
          value: prod-elasticache.nud0cy.0001.use1.cache.amazonaws.com
        - name: CATALOGUE_HOST
          value: catalogue
        - name: CATALOGUE_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    component: user
spec:
  containers:
    - name: user
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/user:2.0.1
      env:
        - name: DOCUMENTDB
          value: "true"
        - name: MONGO_URL
          value: "mongodb://admin1:RoboShop123@prod-docdb.cluster-cbvsbeoyxek4.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
        - name: REDIS_HOST
          value: prod-elasticache.nud0cy.0001.use1.cache.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    component: user
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    component: payment
spec:
  containers:
    - name: payment
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/payment:2.0.0
      env:
        - name: CART_HOST
          value: cart
        - name: CART_PORT
          value: "8080"
        - name: USER_HOST
          value: user
        - name: USER_PORT
          value: "8080"
        - name: AMQP_HOST
          value: prod-rabbitmq.devopsb69.online
        - name: AMQP_USER
          value: roboshop
        - name: AMQP_PASS
          value: roboshop123
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    component: payment
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    component: shipping
spec:
  containers:
    - name: shipping
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/shipping:2.0.0
      env:
        - name: CART_ENDPOINT
          value: cart:8080
        - name: DB_HOST
          value: prod-rds.cluster-cbvsbeoyxek4.us-east-1.rds.amazonaws.com

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    component: shipping
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
  type: ClusterIP
